# Use a valid Java 17 base image
FROM eclipse-temurin:17-jdk-alpine

# Create a writable temp volume
VOLUME /tmp

# Copy your JAR file into the container
COPY target/PhotoAppApiUsers-0.0.1-SNAPSHOT.jar users-microservice.jar

# Run the application
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/users-microservice.jar"]
